...@common.d2

direction: right

Initializing.class: state
BeforeLayout.class: state
CreatingSections.class: state
AfterLayout.class: state

Initializing -> BeforeLayout -> CreatingSections -> AfterLayout: { class: flow }