int foo() { return 0; }
int foo1() { return 1; }
int foo2() { return 2; }
int bar() { return 3; }
int bar1() { return 4; }
int baz() { return 5; }
int qux() { return 6; }
int helper1() { return 7; }
int helper2() { return 8; }
int internal_a() { return 9; }
int internal_b() { return 10; }
