name: Nightly builder for testing eld against musl-test-suite
on:
  schedule:
      - cron: '0 2 * * *' # 2:00 AM
  workflow_dispatch:     # Allows manual triggering
  # pull_request: {} # Uncomment only to test this WF file update.


permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-musl-x86_64:
    if: github.repository == 'qualcomm/eld'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    env:
      ELD_SOURCE_DIR: llvm-project/llvm/tools/eld
    steps:
      - name: Checkout eld
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: llvm-project/llvm/tools/eld

      - name: Configure workflow environment variables
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/ConfigureBuildWorkflowENV

      - name: Record pre-build entry
        if: github.event_name == 'schedule'
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/BuildStatusDataRecorder
        with:
          enabled: true
          project: "llvm-project/llvm/tools/eld"
          stage: "pre-"
          workflow-name: "musl"
          record-mode: "record"
          status: "fail"
          run-id: ${{github.run_id}}
          arch-name: "x86-64"
          branch-name: "${{env.BUILD_BRANCH}}"

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libc++-dev libc++abi-dev \
            libclang-rt-20-dev make

      - name: Set up Clang 20
        uses: egor-tensin/setup-clang@23bc15cd4207e45f1566447deb48f4ff3ef932cb #v2.3
        with:
          version: "20"
          platform: x64

      - name: Verify clang installation
        shell: bash
        run: |
          clang --version
          clang++ --version

      - uses: ./llvm-project/llvm/tools/eld/.github/workflows/FetchNightlyToolset

      - name: Setup ELD Environment
        run: |
          echo "PATH=$PWD/install/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$PWD/obj/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Download and Build musl
        run: |
          git clone --depth 1 https://git.musl-libc.org/git/musl
          cd musl
          CC=clang CXX=clang++ ./configure --prefix=$PWD/../musl-install
          make -j$(nproc)
          make install

      - name: Configure build environment and toolchain
        run: |
          # Set environment variables for subsequent steps
          echo "LD=eld" >> $GITHUB_ENV
          echo "PATH=$PWD/musl-install/bin:$PWD/install/bin:$PATH" >> $GITHUB_ENV
          echo "CC=$PWD/musl-install/bin/musl-clang" >> $GITHUB_ENV
          echo "CFLAGS=-Wno-unused-command-line-argument" >> $GITHUB_ENV

      - name: Download and Setup libc-test
        run: |
          git clone https://repo.or.cz/libc-test.git
          cd libc-test
          STABLE_COMMIT=f2bac7711bec93467b73bec1465579ea0b8d5071
          git checkout ${STABLE_COMMIT}
          cp config.mak.def config.mak
          sed -i 's/LDFLAGS += -g/LDFLAGS += -g -static/' config.mak
          sed -i '1s/$/ -Wno-parentheses/' config.mak

      - name: Build and test libc-test with ELD + musl
        run: |
          cd libc-test
          make -j$(nproc) 2>&1 | tee build.log

      - name: Validate test results with FileCheck
        run: |
          cd libc-test
          FileCheck --check-prefixes=CHECK ../llvm-project/llvm/tools/eld/test/musl/x86_64/static/test-failures.txt < src/REPORT
          FileCheck --check-prefixes=COUNT ../llvm-project/llvm/tools/eld/test/musl/x86_64/static/test-failures.txt < src/REPORT

          echo "Test results validated"

      - name: Update build entry
        if: github.event_name == 'schedule'
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/BuildStatusDataRecorder
        with:
          enabled: true
          project: "llvm-project/llvm/tools/eld"
          stage: "post-"
          workflow-name: "musl"
          record-mode: "update"
          status: "pass"
          run-id: ${{github.run_id}}
          arch-name: "x86-64"
          branch-name: "${{env.BUILD_BRANCH}}"

  test-musl:
    if: github.repository == 'qualcomm/eld'
    strategy:
      fail-fast: false
      matrix:
        arch: [arm, aarch64, riscv32, riscv64]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    env:
      ELD_SOURCE_DIR: ${{ github.workspace }}/llvm-project/llvm/tools/eld
    steps:
      - name: Checkout eld
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: llvm-project/llvm/tools/eld

      - name: Configure workflow environment variables
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/ConfigureBuildWorkflowENV

      - name: Record pre-build entry
        if: github.event_name == 'schedule'
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/BuildStatusDataRecorder
        with:
          enabled: true
          project: "llvm-project/llvm/tools/eld"
          stage: "pre-"
          workflow-name: "musl"
          record-mode: "record"
          status: "fail"
          run-id: ${{github.run_id}}
          arch-name: ${{ matrix.arch }}
          branch-name: "${{env.BUILD_BRANCH}}"

      - uses: ./llvm-project/llvm/tools/eld/.github/workflows/FetchNightlyToolset

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y libc++-dev libc++abi-dev ccache \
            libclang-rt-20-dev cmake ninja-build make qemu-user

      - name: Setup toolchain
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          arm_toolchain_name_suffix=""
          if [[ "${ARCH}" == "arm" ]]; then
            arm_toolchain_name_suffix="eabi"
          fi
          echo "arm_toolchain_name_suffix=${arm_toolchain_name_suffix}" >> $GITHUB_ENV
          wget "https://github.com/cross-tools/clang-cross/releases/download/20251023/${ARCH}-unknown-linux-musl${arm_toolchain_name_suffix}.tar.xz"
          mkdir toolchain
          tar -xvf "${ARCH}-unknown-linux-musl${arm_toolchain_name_suffix}.tar.xz" -C toolchain --strip-components=1
          echo "PATH=$PWD/toolchain/bin:$PATH" >> $GITHUB_ENV
          echo "TOOLCHAIN_ROOT=$(pwd)/toolchain" >> $GITHUB_ENV

      - name: Download musl libc-test
        run: |
          git clone https://repo.or.cz/libc-test.git
          cd libc-test
          STABLE_COMMIT=f2bac7711bec93467b73bec1465579ea0b8d5071
          git checkout ${STABLE_COMMIT}

      - name: Setup musl libc-test environment
        shell: bash
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          cd libc-test
          which grep
          which which
          cp config.mak.def config.mak
          cat >>config.mak <<EOF
            CFLAGS += -Wno-error -Wno-strict-prototypes -Wno-switch-bool -Wno-c23-extensions
            LDFLAGS += --ld-path=$(which ld.eld) -Wl,--image-base=0x1000
          EOF
          cat >"qemu-${ARCH}-wrapper.sh" <<EOF
          #!/usr/bin/bash
          qemu-${ARCH} -L ${TOOLCHAIN_ROOT}/${ARCH}-unknown-linux-musl${arm_toolchain_name_suffix}/sysroot "\$@"
          EOF
          chmod +x "./qemu-${ARCH}-wrapper.sh"
          cat config.mak
          cat "qemu-${ARCH}-wrapper.sh"

      - name: Run musl libc-test suite
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          cd libc-test
          CC="${ARCH}-unknown-linux-musl${arm_toolchain_name_suffix}-clang" make RUN_WRAP="$(pwd)/qemu-${ARCH}-wrapper.sh"

      - name: Upload libc-test
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: libc-test-${{ matrix.arch }}.zip
          # Keep a fallback copy in case the workflow fails before cleanup.
          retention-days: 7
          path: libc-test

      - name: Validate test results with FileCheck
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          cd libc-test
          FileCheck --check-prefixes=CHECK "${ELD_SOURCE_DIR}/test/musl/${ARCH}/test-failures.txt" < src/REPORT
          FileCheck --check-prefixes=COUNT "${ELD_SOURCE_DIR}/test/musl/${ARCH}/test-failures.txt" < src/REPORT
          echo "Test results validated"

      - name: Delete older libc-test artifacts
        continue-on-error: true
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/DeleteOldArtifacts
        with:
          artifact-names: libc-test-${{ matrix.arch }}.zip

      - name: Update build entry
        if: github.event_name == 'schedule'
        uses: ./llvm-project/llvm/tools/eld/.github/workflows/BuildStatusDataRecorder
        with:
          enabled: true
          project: "llvm-project/llvm/tools/eld"
          stage: "post-"
          workflow-name: "musl"
          record-mode: "update"
          status: "pass"
          run-id: ${{github.run_id}}
          arch-name: ${{ matrix.arch }}
          branch-name: "${{env.BUILD_BRANCH}}"
